# <font color =indianred >**HW1 - 15 Points** </font>
- **You have to submit two files for this part of the HW**
  >(1) ipynb (colab notebook) and<br>
  >(2) pdf file (pdf version of the colab file).**
- **Files should be named as follows**:
>FirstName_LastName_HW_1**


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
import torch
import time

# <font color = indianred>**Q1 : Create Tensor (1/2 Point)**
 Create a torch Tensor of shape (5, 3) which is filled with zeros. Modify the tensor to set element (0, 2) to 10 and element (2, 0)  to 100.

In [2]:
my_tensor = torch.zeros(5,3)

In [3]:
my_tensor.shape

torch.Size([5, 3])

In [4]:
my_tensor

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [5]:
my_tensor[0,2] = 10
my_tensor[2,0]=100

In [6]:
my_tensor

tensor([[  0.,   0.,  10.],
        [  0.,   0.,   0.],
        [100.,   0.,   0.],
        [  0.,   0.,   0.],
        [  0.,   0.,   0.]])

# <font color = indianred>**Q2: Reshape tensor (1/2 Point)**
You have following tensor as input:

```x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])```

Using only reshaping functions (like view, reshape, transpose, permute), you need to get at the following tensor as output:

```
tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])
```



In [7]:
x=torch.tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [8]:
x_r=x.view(6,4)
x_r

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

In [9]:
x_f= x_r.transpose(0,1)

In [10]:
x_f

tensor([[ 0,  4,  8, 12, 16, 20],
        [ 1,  5,  9, 13, 17, 21],
        [ 2,  6, 10, 14, 18, 22],
        [ 3,  7, 11, 15, 19, 23]])

# <font color = indianred>**Q3: Slice tensor (1Point)**

- Slice the tensor x to get the following
>- last row of x
>- fourth column of x
>- first three rows and first two columns - the shape of subtensor should be (3,2)
>- odd valued rows and columns

In [11]:
x = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 8, 10], [11, 12, 13, 14, 15]])
x

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  8, 10],
        [11, 12, 13, 14, 15]])

In [12]:
x.shape

torch.Size([3, 5])

In [13]:

last_row = x[-1]
last_row

tensor([11, 12, 13, 14, 15])

In [14]:

fourth_column =x[:,3]
fourth_column

tensor([ 4,  8, 14])

In [15]:

first_3_rows_2_columns = x[0:3,0:2]
first_3_rows_2_columns

tensor([[ 1,  2],
        [ 6,  7],
        [11, 12]])

In [16]:
# Student Task: Retrieve the rows and columns with odd-indexed positions from the tensor 'x'.
# Hint: Use stride slicing to extract the required subset of rows and columns with odd indices.
odd_valued_rows_columns = x[1::2,1::2]
print(odd_valued_rows_columns)


tensor([[7, 8]])


#  <font color = indianred>**Q4 -Normalize Function (1/2 Points)**<font>

Write the function that normalizes the columns of a matrix. You have to compute the mean and standard deviation of each column. Then for each element of the column, you subtract the mean and divide by the standard deviation.

In [17]:
# Given Data
x = [[ 3,  60,  100, -100],
     [ 2,  20,  600, -600],
     [-5,  50,  900, -900]]

In [18]:
# Convert to PyTorch Tensor and set to float
X = torch.tensor(x)
X= X.float()

In [19]:
# Print shape and data type for verification
print(X.shape)
print(X.dtype)

torch.Size([3, 4])
torch.float32


In [20]:
# Compute and display the mean and standard deviation of each column for reference
X.mean(axis = 0)


tensor([   0.0000,   43.3333,  533.3333, -533.3333])

In [21]:
X.std(axis = 0)

tensor([  4.3589,  20.8167, 404.1452, 404.1452])

- Your task starts here
- Your normalize_matrix function should take a PyTorch tensor x as input.
- It should return a tensor where the columns are normalized.
- After implementing your function, use the code provided to verify if the mean for each column in Z is close to zero and the standard deviation is 1.

In [22]:
def normalize_matrix(x):

  mean = x.mean(axis = 0)

  std = x.std(axis = 0)


  y = (x - mean) / std

  return y



In [23]:
Z = normalize_matrix(X)
Z

tensor([[ 0.6882,  0.8006, -1.0722,  1.0722],
        [ 0.4588, -1.1209,  0.1650, -0.1650],
        [-1.1471,  0.3203,  0.9073, -0.9073]])

In [24]:
Z.mean(axis = 0)

tensor([ 0.0000e+00,  4.9671e-08,  3.9736e-08, -3.9736e-08])

# <font color = 'indianred'>**Q5: In-place vs. Out-of-place Operations (1 Point)**

1. Create a tensor `A` with values `[1, 2, 3]`.
2. Perform an in-place addition (use `add_` method) of `5` to tensor `A`.
3. Then, create another tensor `B` with values `[4, 5, 6]` and perform an out-of-place addition of `5`.

**Print the memory addresses of `A` and `B` before and after the operations to demonstrate the difference in memory usage. Provide explanation**


In [25]:
A = torch.tensor([1, 2, 3])
print('Original memory address of A:',A.data_ptr())
A.add_(5)
print('Memory address of A after in-place addition:', A.data_ptr())
print('A after in-place addition:', A)

B = torch.tensor([4, 5, 6])
print('Original memory address of B:',B.data_ptr())
C=B+5
print('Memory address of B after out-of-place addition:', B.data_ptr())
print('B after out-of-place addition:', B)
print('Memory address of new tensor C:', C.data_ptr())
print('C (result of B + 5):', C)


Original memory address of A: 1167770624
Memory address of A after in-place addition: 1167770624
A after in-place addition: tensor([6, 7, 8])
Original memory address of B: 1094317120
Memory address of B after out-of-place addition: 1094317120
B after out-of-place addition: tensor([4, 5, 6])
Memory address of new tensor C: 1167768448
C (result of B + 5): tensor([ 9, 10, 11])


**Provide Explanation for above question here :**




In place operations modify original tensor without changing its memory address.
out of place create a new tensor at different memory address leaving the original unchanged
This shows in place is memory efficient but overwrites the data while out of place is safer and uses more memory


# <font color = 'indianred'>**Q6: Tensor Broadcasting (1 Point)**

1. Create two tensors `X` with shape `(3, 1)` and `Y` with shape `(1, 3)`. Perform an addition operation on `X` and `Y`.
2. Explain how broadcasting is applied in this operation by describing the shape changes that occur internally.

In [26]:
X = torch.tensor([[1], [2], [3]])
Y = torch.tensor([[10, 20, 30]])
print('Original shapes:', X.shape, Y.shape)
result = X+Y
print('Result:', result)
print('Result shape:', result.shape)


Original shapes: torch.Size([3, 1]) torch.Size([1, 3])
Result: tensor([[11, 21, 31],
        [12, 22, 32],
        [13, 23, 33]])
Result shape: torch.Size([3, 3])


**Provide Explanation for above question here :**



X has shape (3,1) and Y has shape (1,3).Pytorch automatically(Broadcast)expands these tensors so their shapes match and element wise addition can be done.

# <font color = 'indianred'>**Q7: Linear Algebra Operations (1 Point)**

1. Create two matrices `M1` and `M2` of compatible shapes for matrix multiplication. Perform the multiplication and print the result.
2. Then, create two vectors `V1` and `V2` and compute their dot product.


In [27]:
M1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
M2 = torch.tensor([[7, 8], [9, 10], [11, 12]])
mat_multiplication =  torch.matmul(M1, M2)
print('Matrix multiplication result:', mat_multiplication)

V1 = torch.tensor([1,2,3])
V2 = torch.tensor([4, 5, 6])
dot_product = torch.dot(V1, V2)
print('Dot product:', dot_product)


Matrix multiplication result: tensor([[ 58,  64],
        [139, 154]])
Dot product: tensor(32)


# <font color = 'indianred'>**Q8: Manipulating Tensor Shapes (1 Point)**

Given a tensor `T` with shape `(2, 3, 4)`, demonstrate how to
1. reshape it to `(3, 8)` using view,
2. reshape it to `(4, 2, 3` using reshape,
3. transpose the first and last dimensions using permute.
4. explain what is the difference between reshape and view

In [28]:
T = torch.rand(2, 3, 4)
T_view =  T.view(3, 8)
print('T_view shape:', T_view.shape)

T_reshape = T.reshape(4, 2, 3)
print('T_reshape shape:', T_reshape.shape)

T_permute =  T.permute(2, 1, 0)
print('T_permute shape:', T_permute.shape)

T_view shape: torch.Size([3, 8])
T_reshape shape: torch.Size([4, 2, 3])
T_permute shape: torch.Size([4, 3, 2])


**Provide Explanation for above question here :**



View requires the tensor to be contiguous in memory(works only on contiguous memory) .If not contiguous it will throw an error.
Reshape also return tensor with different shape just like view but is a lot more flexible.return a view otherwise a copy with the desired shape.
Meaning if tensor is not contiguous .view() fails while.reshape() will still return a copy.


# <font color = 'indianred'>**Q9: Tensor Concatenation and Stacking (1 Point)**

Create tensors `C1` and `C2` both with shape (2, 3).
1. Concatenate them along dimension 0 and then along dimension 1. Print the shape of the resulting tensor.
2. Afterwards, stack the same tensors alomng dimension 0  and print the shape of the resulting tensor.
3. What is the difference between stacking and concatinating.

In [29]:
C1 = torch.rand(2, 3)
C2 = torch.rand(2, 3)
concatenated_dim0 = torch.cat((C1, C2), dim=0)
print('Concatenated along dimension 0:', concatenated_dim0.shape)

concatenated_dim1 =  torch.cat((C1, C2), dim=1)
print('Concatenated along dimension 1:', concatenated_dim1.shape)

stacked =  torch.stack((C1, C2), dim=0)
print('Stacked tensor shape:', stacked.shape)


Concatenated along dimension 0: torch.Size([4, 3])
Concatenated along dimension 1: torch.Size([2, 6])
Stacked tensor shape: torch.Size([2, 2, 3])


**Explain the diffrence between concatinating and stacking here**




Concatenate joins existing tensors along an exisiting dimension,combining their sizes on that dimension
Stacking creates a new dimension and places the input tensors along it.

# <font color = 'indianred'>**Q10: Advanced Indexing and Slicing (1 Point)**

1. Given a tensor `D` with shape (6, 6), extract elements that are greater than 0.5.
2. Then, extract the second and fourth rows from `D`.
3. Finally, extract a sub-tensor from the top-left 3x3 block.

In [30]:
D = torch.rand(6, 6)
elements_gt_0_5 = D[D > 0.5]
print('Elements greater than 0.5:\n',  elements_gt_0_5)

second_fourth_rows =  D[[1, 3], :]
print('\nSecond and fourth rows:\n', second_fourth_rows)

top_left_3x3 =  D[:3, :3]
print('\nTop-left 3x3 block:\n ', top_left_3x3)


Elements greater than 0.5:
 tensor([0.7976, 0.6914, 0.8439, 0.6393, 0.9714, 0.8240, 0.7452, 0.8627, 0.9271,
        0.7740, 0.6263, 0.5538, 0.7562, 0.9916, 0.7973, 0.8847, 0.5980, 0.8209,
        0.5465])

Second and fourth rows:
 tensor([[0.1509, 0.6393, 0.3181, 0.9714, 0.8240, 0.2258],
        [0.9271, 0.4329, 0.3166, 0.7740, 0.6263, 0.4510]])

Top-left 3x3 block:
  tensor([[0.4993, 0.4473, 0.7976],
        [0.1509, 0.6393, 0.3181],
        [0.0032, 0.4694, 0.3127]])


# <font color = 'indianred'>**Q11: Tensor Mathematical Operations (1 Point)**

1. Create a tensor `G` with values from 0 to π in steps of π/4.
2. Compute and print the sine, cosine, and tangent logarithm and the exponential of `G`.

In [31]:
import math

In [32]:
G = G = torch.arange(0, math.pi + 0.0001, math.pi/4)
print('G:', G)
print('Sine of G:', torch.sin(G))
print('Cosine of G:', torch.cos(G))
print('Tangent of G:',  torch.tan(G))


G_no_zero = G.clone()
G_no_zero[G_no_zero == 0] = 1e-10
print('Natural logarithm of G:', torch.log(G_no_zero))
print('Exponential of G:',   torch.exp(G))


G: tensor([0.0000, 0.7854, 1.5708, 2.3562, 3.1416])
Sine of G: tensor([ 0.0000e+00,  7.0711e-01,  1.0000e+00,  7.0711e-01, -8.7423e-08])
Cosine of G: tensor([ 1.0000e+00,  7.0711e-01, -4.3711e-08, -7.0711e-01, -1.0000e+00])
Tangent of G: tensor([ 0.0000e+00,  1.0000e+00, -2.2877e+07, -1.0000e+00,  8.7423e-08])
Natural logarithm of G: tensor([-23.0259,  -0.2416,   0.4516,   0.8570,   1.1447])
Exponential of G: tensor([ 1.0000,  2.1933,  4.8105, 10.5507, 23.1407])


# <font color = 'indianred'>Q12: **Tensor reduction Operations (1 Point)**

1. Create a 3x2 tensor `H`.
2. Compute the sum of `H`. Print the result and shape after taking sun.
3. Then, perform the same operations along dimension 0 and dimension 1, printing the results and shapes.
4. What do you observe? How the shape changes?

In [33]:
H = torch.rand(3, 2)
print('H:', H, end = "\n\n")
print('Shape of original Tensor H', H.shape, end = "\n\n")

total_sum = torch.sum(H)
print('Sum of H:', total_sum)
print('Shape after Sum of H:',total_sum.shape if hasattr(total_sum, 'shape') else 'Scalar (no shape)', end="\n\n")

sum_dim0 = torch.sum(H, dim=0)
print('Sum of H along dimension 0:',  sum_dim0)
print('Shape after sum of H along dimension 0:', sum_dim0.shape,  end = "\n\n")

sum_dim1 = torch.sum(H, dim=1)
print('Sum of H along dimension 1:', sum_dim1)
print('Shape after sum of H along dimension 1:', sum_dim1.shape)


H: tensor([[0.0509, 0.6471],
        [0.5404, 0.3845],
        [0.6621, 0.6585]])

Shape of original Tensor H torch.Size([3, 2])

Sum of H: tensor(2.9435)
Shape after Sum of H: torch.Size([])

Sum of H along dimension 0: tensor([1.2535, 1.6901])
Shape after sum of H along dimension 0: torch.Size([2])

Sum of H along dimension 1: tensor([0.6981, 0.9249, 1.3206])
Shape after sum of H along dimension 1: torch.Size([3])


**Provide your observations on shape changes here**



The entire tensor returns a scalar which means 0 dimensional tensor.
Sum along dimension 1 sums elements down the rows .since original is (3,2) the summing over dim 0 results in shape(2,).
Sum along dimension 1 sums elements across columns .so summing down in shape(3,)

# <font color = 'indianred'>**Q13: Working with Tensor Data Types (1 Point)**

1. Create a tensor `I` of data type float with values `[1.0, 2.0, 3.0]`.
2. Convert `I` to data type int and print the result.
3. Explain in which scenarios it's necessary to be cautious about the data type of tensors.

In [34]:
# Solution for Q16
I = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print('I:', I)
I_int = I.to(torch.int32)
print('I converted to int:', I_int)

I: tensor([1., 2., 3.])
I converted to int: tensor([1, 2, 3], dtype=torch.int32)


**Your explanations here**



Changing from float to int to might cause removal decimal parts, to prevent loss of information.Some operations only work with specific data types using wrong type could cause errors or slow down the program.Choosing the correct type helps with accuracy and memory usage.

# <font color = 'indianred'>**Q14. Speedtest for vectorization 1.5 Points** </font>

Your goal is to measure the speed of linear algebra operations for different levels of vectorization.

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $1024 \times 1024$.
1. Compute $C = A B$ using matrix-matrix operations and report the time. (Hint: Use torch.mm)
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time. (hint use torch.mv inside a for loop)
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time. (Hint: use torch.dot inside nested for loop)

In [35]:
## Solution 1
torch.manual_seed(42) # dod not chnage this
A = torch.randn(1024, 1024)
B = torch.randn(1024, 1024)


In [36]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.06728696823120117 seconds


In [37]:
## Solution 3
C= torch.empty(1024,1024)
start = time.time()

for i in range(B.shape[1]):
    C[:, i] = torch.mv(A, B[:, i])
print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.29874277114868164 seconds


In [38]:
## Solution 4
C= torch.empty(1024,1024)
start = time.time()
for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        C[i, j] = torch.dot(A[i, :], B[:, j])
print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 26.33078670501709 seconds


# <font color = 'indianred'>**Q15 : Redo Question 14 by using GPU - 1.5 Points**

<font size = 4, color = 'indianred'> **Using GPUs**

How to use GPUs in Google Colab<br>
In Google Colab -- Go to Runtime Tab at top -- select change runtime type -- for hardware accelartor choose GPU

In [39]:
# Check if GPU is availaible
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

cuda


In [40]:
## Solution 1
torch.manual_seed(42)
A= torch.randn((1024, 1024),device=device)
B= torch.randn((1024, 1024),device=device)

In [41]:
## Solution 2
start=time.time()

C = torch.mm(A, B)

torch.cuda.synchronize() if device.type == 'cuda' else None
print("Matrix by matrix: " + str(time.time()-start) + " seconds")

Matrix by matrix: 0.12916278839111328 seconds


In [42]:
## Solution 3
C= torch.empty(1024,1024, device = device)
start = time.time()
for i in range(B.shape[1]):
    C[:, i] = torch.mv(A, B[:, i])
torch.cuda.synchronize() if device.type == 'cuda' else None

print("Matrix by vector: " + str(time.time()-start) + " seconds")

Matrix by vector: 0.13579344749450684 seconds


In [43]:
## Solution 4
C= torch.empty(1024,1024, device = device)
start = time.time()

for i in range(A.shape[0]):
    for j in range(B.shape[1]):
        C[i, j] = torch.dot(A[i, :], B[:, j])

if device.type == 'cuda':
    torch.cuda.synchronize()

print("vector by vector: " + str(time.time()-start) + " seconds")

vector by vector: 43.990813970565796 seconds
